/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupTwoFactorRouteImport } from './routes/setup-two-factor'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAuditRouteImport } from './routes/_app/audit'
import { Route as AppRatesRouteImport } from './routes/_app/rates'
import { Route as AppTestCustomersRouteImport } from './routes/_app/test-customers'
import { Route as AppDepositsIndexRouteImport } from './routes/_app/deposits.index'
import { Route as AppDepositsIdRouteImport } from './routes/_app/deposits.$id'
import { Route as AppDepositsTransfersRouteImport } from './routes/_app/deposits.transfers'
import { Route as AppSettingsDepositsRouteImport } from './routes/_app/settings.deposits'
import { Route as AppWalletsIndexRouteImport } from './routes/_app/wallets.index'
import { Route as AppWalletsCustomerIdRouteImport } from './routes/_app/wallets.$customerId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupTwoFactorRoute = SetupTwoFactorRouteImport.update({
  id: '/setup-two-factor',
  path: '/setup-two-factor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppRatesRoute = AppRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AppRoute,
} as any)
const AppTestCustomersRoute = AppTestCustomersRouteImport.update({
  id: '/test-customers',
  path: '/test-customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsIndexRoute = AppDepositsIndexRouteImport.update({
  id: '/deposits/',
  path: '/deposits/',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsIdRoute = AppDepositsIdRouteImport.update({
  id: '/deposits/$id',
  path: '/deposits/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDepositsTransfersRoute = AppDepositsTransfersRouteImport.update({
  id: '/deposits/transfers',
  path: '/deposits/transfers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDepositsRoute = AppSettingsDepositsRouteImport.update({
  id: '/settings/deposits',
  path: '/settings/deposits',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsIndexRoute = AppWalletsIndexRouteImport.update({
  id: '/wallets/',
  path: '/wallets/',
  getParentRoute: () => AppRoute,
} as any)
const AppWalletsCustomerIdRoute = AppWalletsCustomerIdRouteImport.update({
  id: '/wallets/$customerId',
  path: '/wallets/$customerId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/rates': typeof AppRatesRoute
  '/test-customers': typeof AppTestCustomersRoute
  '/deposits/$id': typeof AppDepositsIdRoute
  '/deposits/transfers': typeof AppDepositsTransfersRoute
  '/settings/deposits': typeof AppSettingsDepositsRoute
  '/wallets/$customerId': typeof AppWalletsCustomerIdRoute
  '/deposits/': typeof AppDepositsIndexRoute
  '/wallets/': typeof AppWalletsIndexRoute
}
export interface FileRoutesByTo {
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/account': typeof AppAccountRoute
  '/audit': typeof AppAuditRoute
  '/rates': typeof AppRatesRoute
  '/test-customers': typeof AppTestCustomersRoute
  '/': typeof AppIndexRoute
  '/deposits/$id': typeof AppDepositsIdRoute
  '/deposits/transfers': typeof AppDepositsTransfersRoute
  '/settings/deposits': typeof AppSettingsDepositsRoute
  '/wallets/$customerId': typeof AppWalletsCustomerIdRoute
  '/deposits': typeof AppDepositsIndexRoute
  '/wallets': typeof AppWalletsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/setup-two-factor': typeof SetupTwoFactorRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/audit': typeof AppAuditRoute
  '/_app/rates': typeof AppRatesRoute
  '/_app/test-customers': typeof AppTestCustomersRoute
  '/_app/': typeof AppIndexRoute
  '/_app/deposits/$id': typeof AppDepositsIdRoute
  '/_app/deposits/transfers': typeof AppDepositsTransfersRoute
  '/_app/settings/deposits': typeof AppSettingsDepositsRoute
  '/_app/wallets/$customerId': typeof AppWalletsCustomerIdRoute
  '/_app/deposits/': typeof AppDepositsIndexRoute
  '/_app/wallets/': typeof AppWalletsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/rates'
    | '/test-customers'
    | '/deposits/$id'
    | '/deposits/transfers'
    | '/settings/deposits'
    | '/wallets/$customerId'
    | '/deposits/'
    | '/wallets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/change-password'
    | '/login'
    | '/setup-two-factor'
    | '/account'
    | '/audit'
    | '/rates'
    | '/test-customers'
    | '/'
    | '/deposits/$id'
    | '/deposits/transfers'
    | '/settings/deposits'
    | '/wallets/$customerId'
    | '/deposits'
    | '/wallets'
  id:
    | '__root__'
    | '/_app'
    | '/change-password'
    | '/login'
    | '/setup-two-factor'
    | '/_app/account'
    | '/_app/audit'
    | '/_app/rates'
    | '/_app/test-customers'
    | '/_app/'
    | '/_app/deposits/$id'
    | '/_app/deposits/transfers'
    | '/_app/settings/deposits'
    | '/_app/wallets/$customerId'
    | '/_app/deposits/'
    | '/_app/wallets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  SetupTwoFactorRoute: typeof SetupTwoFactorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-two-factor': {
      id: '/setup-two-factor'
      path: '/setup-two-factor'
      fullPath: '/setup-two-factor'
      preLoaderRoute: typeof SetupTwoFactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/audit': {
      id: '/_app/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rates': {
      id: '/_app/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof AppRatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/test-customers': {
      id: '/_app/test-customers'
      path: '/test-customers'
      fullPath: '/test-customers'
      preLoaderRoute: typeof AppTestCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits/': {
      id: '/_app/deposits/'
      path: '/deposits'
      fullPath: '/deposits/'
      preLoaderRoute: typeof AppDepositsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits/$id': {
      id: '/_app/deposits/$id'
      path: '/deposits/$id'
      fullPath: '/deposits/$id'
      preLoaderRoute: typeof AppDepositsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deposits/transfers': {
      id: '/_app/deposits/transfers'
      path: '/deposits/transfers'
      fullPath: '/deposits/transfers'
      preLoaderRoute: typeof AppDepositsTransfersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/deposits': {
      id: '/_app/settings/deposits'
      path: '/settings/deposits'
      fullPath: '/settings/deposits'
      preLoaderRoute: typeof AppSettingsDepositsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallets/': {
      id: '/_app/wallets/'
      path: '/wallets'
      fullPath: '/wallets/'
      preLoaderRoute: typeof AppWalletsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wallets/$customerId': {
      id: '/_app/wallets/$customerId'
      path: '/wallets/$customerId'
      fullPath: '/wallets/$customerId'
      preLoaderRoute: typeof AppWalletsCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAuditRoute: typeof AppAuditRoute
  AppRatesRoute: typeof AppRatesRoute
  AppTestCustomersRoute: typeof AppTestCustomersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDepositsIdRoute: typeof AppDepositsIdRoute
  AppDepositsTransfersRoute: typeof AppDepositsTransfersRoute
  AppSettingsDepositsRoute: typeof AppSettingsDepositsRoute
  AppWalletsCustomerIdRoute: typeof AppWalletsCustomerIdRoute
  AppDepositsIndexRoute: typeof AppDepositsIndexRoute
  AppWalletsIndexRoute: typeof AppWalletsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAuditRoute: AppAuditRoute,
  AppRatesRoute: AppRatesRoute,
  AppTestCustomersRoute: AppTestCustomersRoute,
  AppIndexRoute: AppIndexRoute,
  AppDepositsIdRoute: AppDepositsIdRoute,
  AppDepositsTransfersRoute: AppDepositsTransfersRoute,
  AppSettingsDepositsRoute: AppSettingsDepositsRoute,
  AppWalletsCustomerIdRoute: AppWalletsCustomerIdRoute,
  AppDepositsIndexRoute: AppDepositsIndexRoute,
  AppWalletsIndexRoute: AppWalletsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  SetupTwoFactorRoute: SetupTwoFactorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
