/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/altcha/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AltchaController_challenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_registration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/send-verification-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/request-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/change-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthAccountController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AuthAccountController_update"];
        trace?: never;
    };
    "/api/admin/test-customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthAdminController_list"];
        put?: never;
        post: operations["AuthAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/test-customers/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthAdminController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminAccountController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/reauthenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminAccountController_reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAccountController_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminAccountController_revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditAdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["RatesAdminController_overview"];
        put?: never;
        post: operations["RatesAdminController_change"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WalletAdminController_adjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallet-adjustments/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WalletAdminController_reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ledger/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/sham-cash/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsController_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/sham-cash/qr/{currency}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsController_qr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/sham-cash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/usdt/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsController_usdtOptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/usdt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_createUsdt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsController_read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/{id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_requote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/{id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_submitReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/{id}/txid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_submitTxid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deposits/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposit-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_readSettings"];
        put: operations["DepositsAdminController_saveSettings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposit-settings/qr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_uploadQr"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposit-settings/qr/{fileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_qr"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_counts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_deposit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/receipts/{receiptId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_receipt"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_approve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/request-receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_requestReceipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/approve-usdt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_approveUsdt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/deposits/{id}/recheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DepositsAdminController_recheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/usdt-transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["DepositsAdminController_transfers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Registration: {
            open: boolean;
        };
        CustomerSignUp: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            phone: string;
        };
        SignUpResult: {
            /** @enum {string} */
            status: "code_sent";
        };
        RequestCode: {
            /** Format: email */
            email: string;
        };
        Success: {
            /** @enum {boolean} */
            success: true;
        };
        ResetPassword: {
            /** Format: email */
            email: string;
            otp: string;
            password: string;
        };
        ChangePassword: {
            currentPassword: string;
            newPassword: string;
        };
        RequestEmailChange: {
            /** Format: email */
            newEmail: string;
            password: string;
        };
        ConfirmEmailChange: {
            /** Format: email */
            newEmail: string;
            otp: string;
        };
        RevokeSession: {
            token: string;
        };
        CustomerProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateCustomerProfile: {
            name?: string;
            phone?: string;
        };
        TestCustomerListQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
        };
        TestCustomerPage: {
            items: components["schemas"]["TestCustomer"][];
            nextCursor: string | null;
        };
        TestCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateTestCustomer: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
        };
        CreatedTestCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
            password: string;
        };
        GeneratedPassword: {
            password: string;
        };
        AdminChangePassword: {
            currentPassword: string;
            newPassword: string;
        };
        Reauthenticate: {
            password: string;
            totpCode: string;
        };
        Reauthentication: {
            /** Format: date-time */
            reauthenticatedUntil: string;
        };
        AdminSessionList: components["schemas"]["AdminSession"][];
        AdminSession: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActiveAt: string;
            /** Format: date-time */
            expiresAt: string;
            ipAddress: string | null;
            userAgent: string | null;
            current: boolean;
        };
        AuditListQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            actorKind?: components["schemas"]["AuditActorKind"];
            /** Format: uuid */
            actorId?: string;
            action?: components["schemas"]["AuditAction"];
            entityType?: components["schemas"]["AuditEntityType"];
            /** Format: uuid */
            entityId?: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        /** @enum {string} */
        AuditActorKind: "admin" | "customer" | "system" | "cli";
        /** @enum {string} */
        AuditAction: "admin.created" | "admin.password_reset" | "admin.two_factor_reset" | "admin.signed_in" | "admin.password_changed" | "admin.two_factor_enabled" | "admin.backup_codes_regenerated" | "admin.sessions_revoked" | "customer.signed_up" | "customer.email_verified" | "customer.profile_updated" | "customer.email_changed" | "customer.password_changed" | "customer.password_reset" | "customer.sessions_revoked" | "customer.test_created" | "customer.test_password_reset" | "wallet_adjustment.created" | "wallet_adjustment.reversed" | "exchange_rate.changed" | "deposit_settings.changed" | "deposit.created" | "deposit.requoted" | "deposit.submitted" | "deposit.cancelled" | "deposit.expired" | "deposit.credited" | "deposit.rejected" | "deposit.receipt_requested" | "deposit.txid_submitted" | "deposit.transfer_bound" | "deposit.txid_bounced" | "deposit.rechecked";
        /** @enum {string} */
        AuditEntityType: "admin_user" | "customer" | "wallet_adjustment" | "exchange_rate" | "deposit_settings" | "deposit";
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            nextCursor: string | null;
        };
        AuditEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            actorKind: components["schemas"]["AuditActorKind"];
            /** Format: uuid */
            actorId: string | null;
            actorName: string | null;
            channel: components["schemas"]["AuditChannel"];
            action: components["schemas"]["AuditAction"];
            entityType: components["schemas"]["AuditEntityType"];
            /** Format: uuid */
            entityId: string;
            reason: string | null;
            details: {
                [key: string]: unknown;
            };
            ipAddress: string | null;
            userAgent: string | null;
        };
        /** @enum {string} */
        AuditChannel: "admin" | "store" | "telegram" | "worker" | "cli";
        RatesOverview: {
            current: components["schemas"]["ExchangeRateRecord"] | null;
            stale: boolean;
            history: components["schemas"]["RatePage"];
        };
        ExchangeRateRecord: {
            /** Format: uuid */
            id: string;
            sypPerUsd: components["schemas"]["ExchangeRate"];
            displayStepSypUnits: number;
            changePercent: string | null;
            adminName: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        ExchangeRate: string;
        RatePage: {
            items: components["schemas"]["ExchangeRateRecord"][];
            nextCursor: string | null;
        };
        ChangeRate: {
            sypPerUsd: components["schemas"]["ExchangeRate"];
            displayStepSypUnits: number;
            rateConfirmation?: string;
        };
        Wallet: {
            balanceUnits: number;
            syp: {
                valueUnits: number;
                rate: components["schemas"]["ExchangeRate"];
            } | null;
        };
        WalletEntryQuery: {
            cursor?: string;
            /** @default 30 */
            limit: number;
        };
        WalletEntryPage: {
            items: components["schemas"]["WalletEntry"][];
            nextCursor: string | null;
        };
        WalletEntry: {
            /** Format: date-time */
            occurredAt: string;
            kind: components["schemas"]["JournalKind"];
            amountUnits: number;
            balanceAfterUnits: number;
            adjustment: {
                category: components["schemas"]["AdjustmentCategory"];
                customerNote: string | null;
                reversal: boolean;
            } | null;
            deposit: {
                method: components["schemas"]["DepositMethod"];
                referenceCode: string;
                syp: {
                    amountUnits: number;
                    rate: components["schemas"]["ExchangeRate"];
                } | null;
            } | null;
        };
        /** @enum {string} */
        JournalKind: "deposit" | "purchase" | "refund" | "cost_of_goods" | "adjustment";
        /** @enum {string} */
        AdjustmentCategory: "compensation" | "correction" | "cash_refund" | "manual_deposit" | "test_funds";
        /** @enum {string} */
        DepositMethod: "sham_cash" | "usdt_trc20" | "usdt_bep20";
        WalletSearchQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            q: string;
        };
        WalletSearchPage: {
            items: components["schemas"]["WalletSearchResult"][];
            nextCursor: string | null;
        };
        WalletSearchResult: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            isTest: boolean;
            balanceUnits: number;
        };
        AdminWallet: {
            balanceUnits: number;
            syp: {
                valueUnits: number;
                rate: components["schemas"]["ExchangeRate"];
            } | null;
            customer: components["schemas"]["WalletCustomer"];
            adjustmentCount: number;
        };
        WalletCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            isTest: boolean;
        };
        AdminWalletEntryPage: {
            items: components["schemas"]["AdminWalletEntry"][];
            nextCursor: string | null;
        };
        AdminWalletEntry: {
            /** Format: date-time */
            occurredAt: string;
            kind: components["schemas"]["JournalKind"];
            amountUnits: number;
            balanceAfterUnits: number;
            /** Format: uuid */
            journalId: string;
            adjustment: {
                category: components["schemas"]["AdjustmentCategory"];
                customerNote: string | null;
                reversal: boolean;
                /** Format: uuid */
                id: string;
                direction: components["schemas"]["AdjustmentDirection"];
                reason: string;
                adminName: string | null;
                depositMethod: components["schemas"]["ManualDepositMethod"] | null;
                externalReference: string | null;
                /** Format: uuid */
                reversesAdjustmentId: string | null;
                /** Format: uuid */
                reversedByAdjustmentId: string | null;
            } | null;
            deposit: {
                method: components["schemas"]["DepositMethod"];
                referenceCode: string;
                syp: {
                    amountUnits: number;
                    rate: components["schemas"]["ExchangeRate"];
                } | null;
                /** Format: uuid */
                id: string;
                txid: string | null;
            } | null;
        };
        /** @enum {string} */
        AdjustmentDirection: "credit" | "debit";
        /** @enum {string} */
        ManualDepositMethod: "sham_cash" | "usdt_trc20" | "usdt_bep20";
        CreateAdjustment: {
            direction: components["schemas"]["AdjustmentDirection"];
            amountUnits: number;
            amountConfirmationUnits?: number;
            category: components["schemas"]["AdjustmentCategory"];
            reason: string;
            customerNote?: string;
            depositMethod?: components["schemas"]["ManualDepositMethod"];
            externalReference?: string;
        };
        Adjustment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            direction: components["schemas"]["AdjustmentDirection"];
            amountUnits: number;
            category: components["schemas"]["AdjustmentCategory"];
            reason: string;
            customerNote: string | null;
            depositMethod: components["schemas"]["ManualDepositMethod"] | null;
            externalReference: string | null;
            /** Format: uuid */
            reversesAdjustmentId: string | null;
            /** Format: uuid */
            journalId: string;
            /** Format: date-time */
            createdAt: string;
            balanceAfterUnits: number;
        };
        ReverseAdjustment: {
            reason: string;
            customerNote?: string;
            amountConfirmationUnits?: number;
        };
        LedgerSummary: {
            owedToCustomersUnits: number;
            owedToTestCustomersUnits: number;
            walletsWithBalance: number;
            systemAccounts: components["schemas"]["SystemAccountBalance"][];
        };
        SystemAccountBalance: {
            kind: components["schemas"]["LedgerAccountKind"];
            code: string;
            currency: components["schemas"]["Currency"];
            balanceUnits: number;
        };
        /** @enum {string} */
        LedgerAccountKind: "customer_wallet" | "sham_cash_receipts" | "usdt_receipts" | "supplier_prepaid" | "sales_revenue" | "cost_of_goods" | "refunds" | "adjustments" | "currency_exchange" | "deposit_rounding";
        /** @enum {string} */
        Currency: "USD" | "SYP";
        ShamCashOptions: {
            currencies: {
                SYP: {
                    available: boolean;
                    /** @enum {string|null} */
                    reason: "not_configured" | "disabled" | "no_rate" | null;
                };
                USD: {
                    available: boolean;
                    /** @enum {string|null} */
                    reason: "not_configured" | "disabled" | "no_rate" | null;
                };
            };
            account: {
                name: string;
                number: string;
            } | null;
            limits: components["schemas"]["DepositLimits"] | null;
            rate: {
                /** Format: uuid */
                id: string;
                sypPerUsd: components["schemas"]["ExchangeRate"];
                displayStepSypUnits: number;
            } | null;
            reviewHours: {
                start: components["schemas"]["ReviewTime"];
                end: components["schemas"]["ReviewTime"];
            } | null;
            eta: components["schemas"]["ReviewEta"] | null;
            /** Format: uuid */
            pendingDepositId: string | null;
        };
        DepositLimits: {
            established: boolean;
            minUnits: number;
            perDepositUnits: number;
            dailyUnits: number;
            remainingTodayUnits: number;
        };
        ReviewTime: string;
        ReviewEta: {
            /** @enum {string} */
            state: "open";
            minutes: number;
        } | {
            /** @enum {string} */
            state: "closed";
            /** Format: date-time */
            opensAt: string;
        };
        CreateShamCashDeposit: {
            currency: components["schemas"]["Currency"];
            amountUnits: number;
        };
        Deposit: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["DepositMethod"];
            status: components["schemas"]["DepositStatus"];
            referenceCode: string;
            currency: components["schemas"]["Currency"];
            declaredAmountUnits: number;
            declaredUsdUnits: number;
            quote: components["schemas"]["DepositQuote"] | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            decidedAt: string | null;
            rateFixed: boolean;
            receiptRequest: {
                /** Format: date-time */
                at: string;
                note: string | null;
            } | null;
            payTo: {
                accountName: string;
                accountNumber: string;
                qrUrl: string | null;
            } | null;
            eta: components["schemas"]["ReviewEta"] | null;
            credited: {
                usdUnits: number;
                receivedCurrency: components["schemas"]["Currency"];
                receivedAmountUnits: number;
                rate: components["schemas"]["ExchangeRate"] | null;
            } | null;
            rejection: {
                reason: components["schemas"]["DepositRejectReason"];
                note: string | null;
            } | null;
            usdt: components["schemas"]["DepositUsdt"] | null;
        };
        /** @enum {string} */
        DepositStatus: "pending" | "submitted" | "credited" | "rejected" | "expired" | "cancelled";
        DepositQuote: {
            /** Format: uuid */
            rateId: string;
            rate: components["schemas"]["ExchangeRate"];
            /** Format: date-time */
            expiresAt: string;
        };
        /** @enum {string} */
        DepositRejectReason: "not_received" | "receipt_invalid" | "receipt_used" | "reference_other_customer" | "wrong_account" | "wrong_network" | "transfer_other_customer" | "other";
        DepositUsdt: {
            method: components["schemas"]["UsdtMethod"];
            address: string;
            payAmount: string;
            payAmountUnits: number;
            checkStatus: components["schemas"]["UsdtCheckStatus"];
            checkError: components["schemas"]["UsdtCheckError"] | null;
            txid: string | null;
            explorerUrl: string | null;
            confirmations: number | null;
            requiredConfirmations: number;
            delayed: boolean;
            receivedAmountUnits: number | null;
            reviewReasons: ("amount_mismatch" | "wrong_network" | "sent_before_deposit")[];
        };
        /** @enum {string} */
        UsdtMethod: "usdt_trc20" | "usdt_bep20";
        /** @enum {string} */
        UsdtCheckStatus: "awaiting_transfer" | "searching" | "confirming" | "review" | "done";
        /** @enum {string} */
        UsdtCheckError: "not_found" | "tx_failed" | "not_to_store" | "wrong_token" | "amount_too_small" | "txid_used";
        UsdtOptions: {
            networks: {
                method: components["schemas"]["UsdtMethod"];
                available: boolean;
                /** @enum {string|null} */
                unavailableReason: "not_configured" | "disabled" | "delayed" | null;
                address: string | null;
                confirmations: number;
            }[];
            limits: components["schemas"]["DepositLimits"] | null;
            /** Format: uuid */
            pendingDepositId: string | null;
        };
        CreateUsdtDeposit: {
            method: components["schemas"]["UsdtMethod"];
            amountUnits: number;
        };
        DepositListQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
        };
        DepositPage: {
            items: components["schemas"]["Deposit"][];
            nextCursor: string | null;
        };
        SubmitReceipt: {
            /** Format: uuid */
            rateId?: string;
        };
        SubmitTxid: {
            txid: string;
        };
        DepositSettings: {
            shamCashAccountName: string;
            shamCashAccountNumber: string;
            sypEnabled: boolean;
            usdEnabled: boolean;
            /** Format: uuid */
            sypQrFileId: string | null;
            /** Format: uuid */
            usdQrFileId: string | null;
            minDepositUsdUnits: number;
            newAccountPerDepositUsdUnits: number;
            newAccountDailyUsdUnits: number;
            establishedPerDepositUsdUnits: number;
            establishedDailyUsdUnits: number;
            reviewHoursStart: components["schemas"]["ReviewTime"];
            reviewHoursEnd: components["schemas"]["ReviewTime"];
            reviewTargetMinutes: number;
            flagNewAccountUsdUnits: number;
            flagVelocityCount: number;
            usdtTrc20Enabled: boolean;
            usdtBep20Enabled: boolean;
            usdtMinDepositUsdUnits: number;
            saved: boolean;
            /** Format: date-time */
            savedAt: string | null;
            usdt: {
                method: components["schemas"]["UsdtMethod"];
                address: string | null;
                /** Format: date-time */
                lastScanAt: string | null;
                delayed: boolean;
            }[];
        };
        DepositSettingsInput: {
            shamCashAccountName: string;
            shamCashAccountNumber: string;
            sypEnabled: boolean;
            usdEnabled: boolean;
            /** Format: uuid */
            sypQrFileId: string | null;
            /** Format: uuid */
            usdQrFileId: string | null;
            minDepositUsdUnits: number;
            newAccountPerDepositUsdUnits: number;
            newAccountDailyUsdUnits: number;
            establishedPerDepositUsdUnits: number;
            establishedDailyUsdUnits: number;
            reviewHoursStart: components["schemas"]["ReviewTime"];
            reviewHoursEnd: components["schemas"]["ReviewTime"];
            reviewTargetMinutes: number;
            flagNewAccountUsdUnits: number;
            flagVelocityCount: number;
            usdtTrc20Enabled: boolean;
            usdtBep20Enabled: boolean;
            usdtMinDepositUsdUnits: number;
        };
        StoredFileRef: {
            /** Format: uuid */
            fileId: string;
        };
        AdminDepositQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            /**
             * @default submitted
             * @enum {string}
             */
            status: "pending" | "submitted" | "credited" | "rejected" | "expired" | "cancelled" | "all";
            /** @enum {string} */
            flagged?: "true" | "false";
            method?: components["schemas"]["DepositMethod"];
            q?: string;
        };
        AdminDepositPage: {
            items: components["schemas"]["AdminDepositListItem"][];
            nextCursor: string | null;
        };
        AdminDepositListItem: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["DepositMethod"];
            status: components["schemas"]["DepositStatus"];
            referenceCode: string;
            currency: components["schemas"]["Currency"];
            declaredAmountUnits: number;
            declaredUsdUnits: number;
            quote: components["schemas"]["DepositQuote"] | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            decidedAt: string | null;
            customer: {
                /** Format: uuid */
                id: string;
                name: string;
                email: string;
                isTest: boolean;
            };
            flags: components["schemas"]["DepositFlagCode"][];
        };
        /** @enum {string} */
        DepositFlagCode: "receipt_reused" | "receipt_similar" | "new_account_large" | "velocity" | "shared_phone" | "amount_mismatch" | "reference_missing" | "reference_different" | "wrong_network" | "sent_before_deposit";
        AdminDepositCounts: {
            submitted: number;
            submittedFlagged: number;
            pending: number;
            usdtReview: number;
            unmatchedTransfers: number;
        };
        AdminDeposit: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["DepositMethod"];
            status: components["schemas"]["DepositStatus"];
            referenceCode: string;
            currency: components["schemas"]["Currency"];
            declaredAmountUnits: number;
            declaredUsdUnits: number;
            quote: components["schemas"]["DepositQuote"] | null;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            submittedAt: string | null;
            /** Format: date-time */
            decidedAt: string | null;
            /** Format: date-time */
            rateFixedAt: string | null;
            /** Format: date-time */
            receiptRequestedAt: string | null;
            receiptRequestCount: number;
            receiptRequestNote: string | null;
            approvalRate: {
                /** Format: uuid */
                rateId: string;
                rate: components["schemas"]["ExchangeRate"];
            } | null;
            decidedBy: components["schemas"]["DepositDecider"] | null;
            adminName: string | null;
            credit: {
                transactionNumber: string;
                receivedCurrency: components["schemas"]["Currency"];
                receivedAmountUnits: number;
                creditedUsdUnits: number;
                /** Format: uuid */
                creditRateId: string | null;
                creditRate: components["schemas"]["ExchangeRate"] | null;
                referenceCheck: components["schemas"]["DepositReferenceCheck"] | null;
                /** Format: uuid */
                journalId: string;
            } | null;
            rejection: {
                reason: components["schemas"]["DepositRejectReason"];
                customerNote: string | null;
            } | null;
            receipts: {
                /** Format: uuid */
                id: string;
                /** Format: date-time */
                createdAt: string;
            }[];
            flags: components["schemas"]["DepositFlag"][];
            customer: {
                /** Format: uuid */
                id: string;
                name: string;
                email: string;
                isTest: boolean;
                phone: string;
                /** Format: date-time */
                createdAt: string;
                established: boolean;
                creditedCount: number;
                creditedTotalUsdUnits: number;
                balanceUnits: number;
                recentDeposits: {
                    /** Format: uuid */
                    id: string;
                    referenceCode: string;
                    status: components["schemas"]["DepositStatus"];
                    currency: components["schemas"]["Currency"];
                    declaredAmountUnits: number;
                    /** Format: date-time */
                    createdAt: string;
                }[];
            };
            eta: components["schemas"]["ReviewEta"] | null;
            usdt: components["schemas"]["AdminDepositUsdt"] | null;
        };
        /** @enum {string} */
        DepositDecider: "admin" | "system";
        /** @enum {string} */
        DepositReferenceCheck: "matches" | "missing" | "different";
        DepositFlag: {
            /** Format: uuid */
            id: string;
            code: components["schemas"]["DepositFlagCode"];
            /** Format: uuid */
            receiptId: string | null;
            details: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AdminDepositUsdt: {
            method: components["schemas"]["UsdtMethod"];
            address: string;
            payAmount: string;
            payAmountUnits: number;
            checkStatus: components["schemas"]["UsdtCheckStatus"];
            checkError: components["schemas"]["UsdtCheckError"] | null;
            txid: string | null;
            explorerUrl: string | null;
            confirmations: number | null;
            requiredConfirmations: number;
            delayed: boolean;
            receivedAmountUnits: number | null;
            reviewReasons: ("amount_mismatch" | "wrong_network" | "sent_before_deposit")[];
            tailUnits: number;
            txidSource: components["schemas"]["UsdtTxidSource"] | null;
            txidSubmissions: number;
            /** Format: date-time */
            lastCheckedAt: string | null;
            transfer: components["schemas"]["UsdtTransfer"] | null;
            candidates: components["schemas"]["UsdtCandidate"][];
        };
        /** @enum {string} */
        UsdtTxidSource: "customer" | "scan";
        UsdtTransfer: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["UsdtMethod"];
            txid: string;
            explorerUrl: string;
            fromAddress: string;
            toAddress: string;
            rawAmount: string;
            amountUnits: number;
            blockNumber: number;
            /** Format: date-time */
            blockTime: string;
            source: components["schemas"]["UsdtTransferSource"];
            /** Format: date-time */
            createdAt: string;
        };
        /** @enum {string} */
        UsdtTransferSource: "scan" | "txid";
        UsdtCandidate: {
            /** Format: uuid */
            depositId: string;
            referenceCode: string;
            status: components["schemas"]["DepositStatus"];
            payAmountUnits: number;
            /** Format: date-time */
            createdAt: string;
            customer: {
                /** Format: uuid */
                id: string;
                name: string;
                email: string;
            };
        };
        ApproveDeposit: {
            transactionNumber: string;
            receivedCurrency: components["schemas"]["Currency"];
            receivedAmountUnits: number;
            referenceCheck: components["schemas"]["DepositReferenceCheck"];
            acknowledgedFlags: components["schemas"]["DepositFlagCode"][];
            internalNote?: string;
        };
        RejectDeposit: {
            reason: components["schemas"]["DepositRejectReason"];
            customerNote?: string;
            internalNote: string;
        };
        RequestReceipt: {
            customerNote?: string;
            internalNote: string;
        };
        ApproveUsdtDeposit: {
            acknowledgedFlags: components["schemas"]["DepositFlagCode"][];
            internalNote?: string;
        };
        AdminUsdtTransferQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            method?: components["schemas"]["UsdtMethod"];
            /**
             * @default unmatched
             * @enum {string}
             */
            state: "unmatched" | "all";
        };
        AdminUsdtTransferPage: {
            items: components["schemas"]["AdminUsdtTransfer"][];
            nextCursor: string | null;
        };
        AdminUsdtTransfer: {
            /** Format: uuid */
            id: string;
            method: components["schemas"]["UsdtMethod"];
            txid: string;
            explorerUrl: string;
            fromAddress: string;
            toAddress: string;
            rawAmount: string;
            amountUnits: number;
            blockNumber: number;
            /** Format: date-time */
            blockTime: string;
            source: components["schemas"]["UsdtTransferSource"];
            /** Format: date-time */
            createdAt: string;
            state: components["schemas"]["UsdtTransferState"];
            holder: {
                /** @enum {string} */
                kind: "deposit" | "adjustment";
                /** Format: uuid */
                id: string;
                customer: {
                    /** Format: uuid */
                    id: string;
                    name: string;
                    email: string;
                };
            } | null;
            candidates: components["schemas"]["UsdtCandidate"][];
        };
        /** @enum {string} */
        UsdtTransferState: "credited" | "bound" | "unmatched";
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
            };
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AltchaController_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A signed ALTCHA challenge for the widget (ADR 0008) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether customers can sign up (rule C16) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignUp"];
            };
        };
        responses: {
            /** @description A code was sent (rule C2) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResult"];
                };
            };
        };
    };
    AuthController_sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCode"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCode"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPassword"];
            };
        };
        responses: {
            /** @description Set; every session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Changed; other sessions are signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_requestEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEmailChange"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_confirmEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChange"];
            };
        };
        responses: {
            /** @description Changed; other sessions are signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeSession"];
            };
        };
        responses: {
            /** @description The session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthAccountController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
        };
    };
    AuthAccountController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerProfile"];
            };
        };
        responses: {
            /** @description The updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
        };
    };
    AuthAdminController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCustomerPage"];
                };
            };
        };
    };
    AuthAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestCustomer"];
            };
        };
        responses: {
            /** @description The customer and its password, once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedTestCustomer"];
                };
            };
        };
    };
    AuthAdminController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new password, once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedPassword"];
                };
            };
        };
    };
    AdminAccountController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChangePassword"];
            };
        };
        responses: {
            /** @description Changed; other sessions end */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AdminAccountController_reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reauthenticate"];
            };
        };
        responses: {
            /** @description Sensitive routes are open until then */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reauthentication"];
                };
            };
        };
    };
    AdminAccountController_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The admin’s sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionList"];
                };
            };
        };
    };
    AdminAccountController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditAdminController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                actorKind?: "admin" | "customer" | "system" | "cli";
                actorId?: string;
                action?: "admin.created" | "admin.password_reset" | "admin.two_factor_reset" | "admin.signed_in" | "admin.password_changed" | "admin.two_factor_enabled" | "admin.backup_codes_regenerated" | "admin.sessions_revoked" | "customer.signed_up" | "customer.email_verified" | "customer.profile_updated" | "customer.email_changed" | "customer.password_changed" | "customer.password_reset" | "customer.sessions_revoked" | "customer.test_created" | "customer.test_password_reset" | "wallet_adjustment.created" | "wallet_adjustment.reversed" | "exchange_rate.changed" | "deposit_settings.changed" | "deposit.created" | "deposit.requoted" | "deposit.submitted" | "deposit.cancelled" | "deposit.expired" | "deposit.credited" | "deposit.rejected" | "deposit.receipt_requested" | "deposit.txid_submitted" | "deposit.transfer_bound" | "deposit.txid_bounced" | "deposit.rechecked";
                entityType?: "admin_user" | "customer" | "wallet_adjustment" | "exchange_rate" | "deposit_settings" | "deposit";
                entityId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
        };
    };
    RatesAdminController_overview: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current rate and the history, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RatesOverview"];
                };
            };
        };
    };
    RatesAdminController_change: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRate"];
            };
        };
        responses: {
            /** @description The new rate */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExchangeRateRecord"];
                };
            };
        };
    };
    WalletController_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    WalletController_entries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletEntryPage"];
                };
            };
        };
    };
    WalletAdminController_search: {
        parameters: {
            query: {
                cursor?: string;
                limit?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest customers first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletSearchPage"];
                };
            };
        };
    };
    WalletAdminController_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The wallet and its customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWallet"];
                };
            };
        };
    };
    WalletAdminController_entries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWalletEntryPage"];
                };
            };
        };
    };
    WalletAdminController_adjust: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdjustment"];
            };
        };
        responses: {
            /** @description Written (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
        };
    };
    WalletAdminController_reverse: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseAdjustment"];
            };
        };
        responses: {
            /** @description The reversal (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
        };
    };
    WalletAdminController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the store owes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerSummary"];
                };
            };
        };
    };
    DepositsController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the wizard offers now */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShamCashOptions"];
                };
            };
        };
    };
    DepositsController_qr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                currency: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The QR image of an enabled currency */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepositsController_create: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShamCashDeposit"];
            };
        };
        responses: {
            /** @description Created (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_usdtOptions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The USDT networks now */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsdtOptions"];
                };
            };
        };
    };
    DepositsController_createUsdt: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUsdtDeposit"];
            };
        };
        responses: {
            /** @description Created (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositPage"];
                };
            };
        };
    };
    DepositsController_read: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deposit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_requote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A new 15-minute quote */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_submitReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SubmitReceipt"];
            };
        };
        responses: {
            /** @description Submitted for review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_submitTxid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitTxid"];
            };
        };
        responses: {
            /** @description Verification started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deposit"];
                };
            };
        };
    };
    DepositsAdminController_readSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description In force, or the defaults */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositSettings"];
                };
            };
        };
    };
    DepositsAdminController_saveSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DepositSettingsInput"];
            };
        };
        responses: {
            /** @description The new version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepositSettings"];
                };
            };
        };
    };
    DepositsAdminController_uploadQr: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description The re-encoded PNG */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredFileRef"];
                };
            };
        };
    };
    DepositsAdminController_qr: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A QR image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepositsAdminController_queue: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                status?: "pending" | "submitted" | "credited" | "rejected" | "expired" | "cancelled" | "all";
                flagged?: "true" | "false";
                method?: "sham_cash" | "usdt_trc20" | "usdt_bep20";
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rule RV10 order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDepositPage"];
                };
            };
        };
    };
    DepositsAdminController_counts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The navigation badge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDepositCounts"];
                };
            };
        };
    };
    DepositsAdminController_deposit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The deposit and its review */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_receipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                receiptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The re-encoded receipt */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DepositsAdminController_approve: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveDeposit"];
            };
        };
        responses: {
            /** @description Credited (or its replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_reject: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectDeposit"];
            };
        };
        responses: {
            /** @description Rejected (or its replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_requestReceipt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestReceipt"];
            };
        };
        responses: {
            /** @description Back to pending */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_approveUsdt: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApproveUsdtDeposit"];
            };
        };
        responses: {
            /** @description Credited (or its replay) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_recheck: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Verification sent again */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminDeposit"];
                };
            };
        };
    };
    DepositsAdminController_transfers: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                method?: "usdt_trc20" | "usdt_bep20";
                state?: "unmatched" | "all";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUsdtTransferPage"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its dependencies are up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
