/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/altcha/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AltchaController_challenge"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/registration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_registration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/send-verification-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendVerificationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/request-email-change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/email-otp/change-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_confirmEmailChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_revokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthAccountController_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AuthAccountController_update"];
        trace?: never;
    };
    "/api/admin/test-customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthAdminController_list"];
        put?: never;
        post: operations["AuthAdminController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/test-customers/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthAdminController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminAccountController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/reauthenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminAccountController_reauthenticate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminAccountController_sessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/me/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminAccountController_revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuditAdminController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletController_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_wallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallets/{customerId}/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WalletAdminController_adjust"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/wallet-adjustments/{id}/reverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WalletAdminController_reverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ledger/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WalletAdminController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Registration: {
            open: boolean;
        };
        CustomerSignUp: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
            phone: string;
        };
        SignUpResult: {
            /** @enum {string} */
            status: "code_sent";
        };
        RequestCode: {
            /** Format: email */
            email: string;
        };
        Success: {
            /** @enum {boolean} */
            success: true;
        };
        ResetPassword: {
            /** Format: email */
            email: string;
            otp: string;
            password: string;
        };
        ChangePassword: {
            currentPassword: string;
            newPassword: string;
        };
        RequestEmailChange: {
            /** Format: email */
            newEmail: string;
            password: string;
        };
        ConfirmEmailChange: {
            /** Format: email */
            newEmail: string;
            otp: string;
        };
        RevokeSession: {
            token: string;
        };
        CustomerProfile: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
        };
        UpdateCustomerProfile: {
            name?: string;
            phone?: string;
        };
        TestCustomerListQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
        };
        TestCustomerPage: {
            items: components["schemas"]["TestCustomer"][];
            nextCursor: string | null;
        };
        TestCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateTestCustomer: {
            name: string;
            /** Format: email */
            email: string;
            phone: string;
        };
        CreatedTestCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone: string;
            /** Format: date-time */
            createdAt: string;
            password: string;
        };
        GeneratedPassword: {
            password: string;
        };
        AdminChangePassword: {
            currentPassword: string;
            newPassword: string;
        };
        Reauthenticate: {
            password: string;
            totpCode: string;
        };
        Reauthentication: {
            /** Format: date-time */
            reauthenticatedUntil: string;
        };
        AdminSessionList: components["schemas"]["AdminSession"][];
        AdminSession: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastActiveAt: string;
            /** Format: date-time */
            expiresAt: string;
            ipAddress: string | null;
            userAgent: string | null;
            current: boolean;
        };
        AuditListQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            actorKind?: components["schemas"]["AuditActorKind"];
            /** Format: uuid */
            actorId?: string;
            action?: components["schemas"]["AuditAction"];
            entityType?: components["schemas"]["AuditEntityType"];
            /** Format: uuid */
            entityId?: string;
            /** Format: date-time */
            from?: string;
            /** Format: date-time */
            to?: string;
        };
        /** @enum {string} */
        AuditActorKind: "admin" | "customer" | "system" | "cli";
        /** @enum {string} */
        AuditAction: "admin.created" | "admin.password_reset" | "admin.two_factor_reset" | "admin.signed_in" | "admin.password_changed" | "admin.two_factor_enabled" | "admin.backup_codes_regenerated" | "admin.sessions_revoked" | "customer.signed_up" | "customer.email_verified" | "customer.profile_updated" | "customer.email_changed" | "customer.password_changed" | "customer.password_reset" | "customer.sessions_revoked" | "customer.test_created" | "customer.test_password_reset" | "wallet_adjustment.created" | "wallet_adjustment.reversed";
        /** @enum {string} */
        AuditEntityType: "admin_user" | "customer" | "wallet_adjustment";
        AuditPage: {
            items: components["schemas"]["AuditEntry"][];
            nextCursor: string | null;
        };
        AuditEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            actorKind: components["schemas"]["AuditActorKind"];
            /** Format: uuid */
            actorId: string | null;
            actorName: string | null;
            channel: components["schemas"]["AuditChannel"];
            action: components["schemas"]["AuditAction"];
            entityType: components["schemas"]["AuditEntityType"];
            /** Format: uuid */
            entityId: string;
            reason: string | null;
            details: {
                [key: string]: unknown;
            };
            ipAddress: string | null;
            userAgent: string | null;
        };
        /** @enum {string} */
        AuditChannel: "admin" | "store" | "telegram" | "worker" | "cli";
        Wallet: {
            balanceUnits: number;
            syp: {
                valueUnits: number;
                rate: components["schemas"]["ExchangeRate"];
            } | null;
        };
        ExchangeRate: string;
        WalletEntryQuery: {
            cursor?: string;
            /** @default 30 */
            limit: number;
        };
        WalletEntryPage: {
            items: components["schemas"]["WalletEntry"][];
            nextCursor: string | null;
        };
        WalletEntry: {
            /** Format: date-time */
            occurredAt: string;
            kind: components["schemas"]["JournalKind"];
            amountUnits: number;
            balanceAfterUnits: number;
            adjustment: {
                category: components["schemas"]["AdjustmentCategory"];
                customerNote: string | null;
                reversal: boolean;
            } | null;
        };
        /** @enum {string} */
        JournalKind: "deposit" | "purchase" | "refund" | "cost_of_goods" | "adjustment";
        /** @enum {string} */
        AdjustmentCategory: "compensation" | "correction" | "cash_refund" | "manual_deposit" | "test_funds";
        WalletSearchQuery: {
            cursor?: string;
            /** @default 50 */
            limit: number;
            q: string;
        };
        WalletSearchPage: {
            items: components["schemas"]["WalletSearchResult"][];
            nextCursor: string | null;
        };
        WalletSearchResult: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            isTest: boolean;
            balanceUnits: number;
        };
        AdminWallet: {
            balanceUnits: number;
            syp: {
                valueUnits: number;
                rate: components["schemas"]["ExchangeRate"];
            } | null;
            customer: components["schemas"]["WalletCustomer"];
            adjustmentCount: number;
        };
        WalletCustomer: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
            phone: string;
            isTest: boolean;
        };
        AdminWalletEntryPage: {
            items: components["schemas"]["AdminWalletEntry"][];
            nextCursor: string | null;
        };
        AdminWalletEntry: {
            /** Format: date-time */
            occurredAt: string;
            kind: components["schemas"]["JournalKind"];
            amountUnits: number;
            balanceAfterUnits: number;
            /** Format: uuid */
            journalId: string;
            adjustment: {
                category: components["schemas"]["AdjustmentCategory"];
                customerNote: string | null;
                reversal: boolean;
                /** Format: uuid */
                id: string;
                direction: components["schemas"]["AdjustmentDirection"];
                reason: string;
                adminName: string | null;
                depositMethod: components["schemas"]["ManualDepositMethod"] | null;
                externalReference: string | null;
                /** Format: uuid */
                reversesAdjustmentId: string | null;
                /** Format: uuid */
                reversedByAdjustmentId: string | null;
            } | null;
        };
        /** @enum {string} */
        AdjustmentDirection: "credit" | "debit";
        /** @enum {string} */
        ManualDepositMethod: "sham_cash" | "usdt_trc20" | "usdt_bep20";
        CreateAdjustment: {
            direction: components["schemas"]["AdjustmentDirection"];
            amountUnits: number;
            amountConfirmationUnits?: number;
            category: components["schemas"]["AdjustmentCategory"];
            reason: string;
            customerNote?: string;
            depositMethod?: components["schemas"]["ManualDepositMethod"];
            externalReference?: string;
        };
        Adjustment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            customerId: string;
            direction: components["schemas"]["AdjustmentDirection"];
            amountUnits: number;
            category: components["schemas"]["AdjustmentCategory"];
            reason: string;
            customerNote: string | null;
            depositMethod: components["schemas"]["ManualDepositMethod"] | null;
            externalReference: string | null;
            /** Format: uuid */
            reversesAdjustmentId: string | null;
            /** Format: uuid */
            journalId: string;
            /** Format: date-time */
            createdAt: string;
            balanceAfterUnits: number;
        };
        ReverseAdjustment: {
            reason: string;
            customerNote?: string;
            amountConfirmationUnits?: number;
        };
        LedgerSummary: {
            owedToCustomersUnits: number;
            owedToTestCustomersUnits: number;
            walletsWithBalance: number;
            systemAccounts: components["schemas"]["SystemAccountBalance"][];
        };
        SystemAccountBalance: {
            kind: components["schemas"]["LedgerAccountKind"];
            code: string;
            currency: components["schemas"]["Currency"];
            balanceUnits: number;
        };
        /** @enum {string} */
        LedgerAccountKind: "customer_wallet" | "sham_cash_receipts" | "usdt_receipts" | "supplier_prepaid" | "sales_revenue" | "cost_of_goods" | "refunds" | "adjustments";
        /** @enum {string} */
        Currency: "USD" | "SYP";
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            checks: {
                /** @enum {string} */
                database: "up" | "down";
            };
            /** Format: date-time */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AltchaController_challenge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A signed ALTCHA challenge for the widget (ADR 0008) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_registration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Whether customers can sign up (rule C16) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Registration"];
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerSignUp"];
            };
        };
        responses: {
            /** @description A code was sent (rule C2) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResult"];
                };
            };
        };
    };
    AuthController_sendVerificationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCode"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCode"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPassword"];
            };
        };
        responses: {
            /** @description Set; every session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePassword"];
            };
        };
        responses: {
            /** @description Changed; other sessions are signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_requestEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestEmailChange"];
            };
        };
        responses: {
            /** @description Always, whether or not a code was sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_confirmEmailChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmEmailChange"];
            };
        };
        responses: {
            /** @description Changed; other sessions are signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevokeSession"];
            };
        };
        responses: {
            /** @description The session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthController_revokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every session is signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AuthAccountController_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
        };
    };
    AuthAccountController_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerProfile"];
            };
        };
        responses: {
            /** @description The updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerProfile"];
                };
            };
        };
    };
    AuthAdminController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestCustomerPage"];
                };
            };
        };
    };
    AuthAdminController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestCustomer"];
            };
        };
        responses: {
            /** @description The customer and its password, once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedTestCustomer"];
                };
            };
        };
    };
    AuthAdminController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new password, once */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedPassword"];
                };
            };
        };
    };
    AdminAccountController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminChangePassword"];
            };
        };
        responses: {
            /** @description Changed; other sessions end */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Success"];
                };
            };
        };
    };
    AdminAccountController_reauthenticate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Reauthenticate"];
            };
        };
        responses: {
            /** @description Sensitive routes are open until then */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reauthentication"];
                };
            };
        };
    };
    AdminAccountController_sessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The admin’s sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionList"];
                };
            };
        };
    };
    AdminAccountController_revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuditAdminController_list: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
                actorKind?: "admin" | "customer" | "system" | "cli";
                actorId?: string;
                action?: "admin.created" | "admin.password_reset" | "admin.two_factor_reset" | "admin.signed_in" | "admin.password_changed" | "admin.two_factor_enabled" | "admin.backup_codes_regenerated" | "admin.sessions_revoked" | "customer.signed_up" | "customer.email_verified" | "customer.profile_updated" | "customer.email_changed" | "customer.password_changed" | "customer.password_reset" | "customer.sessions_revoked" | "customer.test_created" | "customer.test_password_reset" | "wallet_adjustment.created" | "wallet_adjustment.reversed";
                entityType?: "admin_user" | "customer" | "wallet_adjustment";
                entityId?: string;
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
        };
    };
    WalletController_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The balance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    WalletController_entries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletEntryPage"];
                };
            };
        };
    };
    WalletAdminController_search: {
        parameters: {
            query: {
                cursor?: string;
                limit?: number;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest customers first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WalletSearchPage"];
                };
            };
        };
    };
    WalletAdminController_wallet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The wallet and its customer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWallet"];
                };
            };
        };
    };
    WalletAdminController_entries: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWalletEntryPage"];
                };
            };
        };
    };
    WalletAdminController_adjust: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                customerId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdjustment"];
            };
        };
        responses: {
            /** @description Written (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
        };
    };
    WalletAdminController_reverse: {
        parameters: {
            query?: never;
            header: {
                /** @description A UUID per attempt; a retry with the same key returns the first result */
                "Idempotency-Key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReverseAdjustment"];
            };
        };
        responses: {
            /** @description The reversal (200: a replay) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Adjustment"];
                };
            };
        };
    };
    WalletAdminController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What the store owes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerSummary"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API and its dependencies are up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description A dependency is down */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
